### ISSUE TITLE
open source code 

### ISSUE THREAD

**Issue by zdz0086** [ispamm/MHyEEG#1]
Hello, when will your code be open source, thank you

**Comment by NEO-SH1W4** [comment]
Olá, Quero colabora!

**Comment by liuyyanan** [comment]
hello, where is your open code? there is no code for the work,  when it would be published? thanks for your sharing.

**Comment by elelo22** [comment]
Hi, so sorry for the late reply, we'll publish the code as soon as possible (within the month) :)

**Comment by elelo22** [comment]
Hi, we have uploaded all the code as well as instructions on how to use it :)
