### ISSUE TITLE
about dataset

### ISSUE THREAD

**Issue by wobizhuanhang** [ispamm/MHyEEG#6]

**Comment by wenjiu100** [comment]
Hello, can you share the dataset you have? my Email is 838816810@qq.com. or can you share the way or LINK to get it? I've been applying on the official side for a couple weeks and never got a response. Thanks.

**Comment by elelo22** [comment]
Hi, unfortunately, I'm not allowed to share it as it is a private dataset and you need to get access from the managers of the database. Keep trying and if you have the possibility, try to ask permission via a professor. There are also other datasets similar to this one, you can also try to ask access for those datasets!
